-- Q1. What is the total revenue generated by male and female customers?
SELECT
    gender,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY gender
ORDER BY total_revenue DESC;

-- Q2. Which customers used a discount but still spent more than the overall average purchase amount?
SELECT
    customer_id,
    purchase_amount
FROM customer
WHERE discount_applied = 'Yes'
AND purchase_amount >= (
    SELECT AVG(purchase_amount)
    FROM customer
)
ORDER BY purchase_amount DESC;

-- Q3. Which are the top 5 products with the highest average customer review ratings?
SELECT
    item_purchased,
    ROUND(AVG(review_rating::numeric),2) AS average_review_rating
FROM customer
GROUP BY item_purchased
ORDER BY average_review_rating DESC
LIMIT 5;

-- Q4. How does the average purchase amount compare between Standard Shipping and Express Shipping?
SELECT
    shipping_type,
    ROUND(AVG(purchase_amount),2) AS average_purchase_amount
FROM customer
WHERE shipping_type IN ('Standard','Express')
GROUP BY shipping_type
ORDER BY average_purchase_amount DESC;

-- Q5. Do subscribed customers spend more than non-subscribed customers? Compare the total number of customers, average purchase amount, and total revenue generated by each group.
SELECT
    subscription_status,
    COUNT(customer_id) AS total_customers,
    ROUND(AVG(purchase_amount),2) AS average_purchase_amount,
    ROUND(SUM(purchase_amount),2) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue DESC;

-- Q6. Which five products have the highest percentage of purchases made using discounts?
SELECT
    item_purchased,
    ROUND(
        100.0 *
        SUM(CASE WHEN discount_applied='Yes' THEN 1 ELSE 0 END)
        / COUNT(*),
        2
    ) AS discount_percentage
FROM customer
GROUP BY item_purchased
ORDER BY discount_percentage DESC
LIMIT 5;

-- Q7. Segment customers into New, Returning, and Loyal categories based on the number of previous purchases, and determine the number of customers in each segment.
with customer_type as (
SELECT customer_id, previous_purchases,
CASE 
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
FROM customer)

select customer_segment,count(*) AS "Number of Customers" 
from customer_type 
group by customer_segment;

-- Q8. What are the top three most purchased products within each product category?
WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT item_rank,category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;

-- Q9. Are repeat buyers (customers with more than five previous purchases) more likely to have an active subscription?
SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- Q10. What is the total revenue contribution of each customer age group?
SELECT 
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue desc;
